feat(Home): unit test for models

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -10,4 +10,9 @@ if [ $? -ne 0 ]; then
   printf "\e[31;1m%s\e[0m\n" 'Flutter analyzer error'
   exit 1
 fi
+flutter test
+if [ $? -ne 0 ]; then
+  printf "\e[31;1m%s\e[0m\n" 'Flutter test error'
+  exit 1
+fi
 printf "\e[33;1m%s\e[0m\n" 'Finished running the Flutter analyzer'
